import {NgModule} from '@angular/core';
import { Column } from './modules/iggrid/column.directive';
import { IgGridMultiColumnHeadersFeature } from './modules/iggrid/iggridfeatures/iggridmulticolumnheaders.directive';
import { IgGridSortingFeature } from './modules/iggrid/iggridfeatures/iggridsorting.directive';
import { IgGridFilteringFeature } from './modules/iggrid/iggridfeatures/iggridfiltering.directive';
import { IgGridPagingFeature } from './modules/iggrid/iggridfeatures/iggridpaging.directive';
import { IgGridUpdatingFeature } from './modules/iggrid/iggridfeatures/iggridupdating.directive';
import { IgGridGroupByFeature } from './modules/iggrid/iggridfeatures/iggridgroupby.directive';
import { IgGridColumnMovingFeature } from './modules/iggrid/iggridfeatures/iggridcolumnmoving';
import { IgGridHidingFeature } from './modules/iggrid/iggridfeatures/iggridhiding.directive';
import { IgGridCellMergingFeature } from './modules/iggrid/iggridfeatures/iggridcellmerging.directive';
import { IgGridResponsiveFeature } from './modules/iggrid/iggridfeatures/iggridresponsive.directive';
import { IgGridResizingFeature } from './modules/iggrid/iggridfeatures/iggridresizing.directive';
import { IgGridSelectionFeature } from './modules/iggrid/iggridfeatures/iggridselection.directive';
import { IgGridRowSelectorsFeature } from './modules/iggrid/iggridfeatures/iggridrowselectors.directive';
import { IgGridSummariesFeature } from './modules/iggrid/iggridfeatures/iggridsummaries.directive';
import { IgGridColumnFixingFeature } from './modules/iggrid/iggridfeatures/iggridcolumnfixing.directive';
import { IgGridTooltipsFeature } from './modules/iggrid/iggridfeatures/iggridtooltips.directive';
import { IgGridAppendRowsOnDemandFeature } from './modules/iggrid/iggridfeatures/iggridappendrowsondemand.directive';
import { Features } from './modules/iggrid/features.directive';
import { IgGridComponent } from './modules/iggrid/iggrid.component';
import { IgTreeGridComponent } from './modules/igtreegrid/igtreegrid.component';
import { IgHierarchicalGridComponent } from './modules/ighierarchicalgrid/ighierarchicalgrid.component';
import { IgComboComponent } from './modules/igcombo/igcombo.component';
import { IgCheckboxEditorComponent } from './modules/igeditors/igcheckboxeditor.component';
import { IgCurrencyEditorComponent } from './modules/igeditors/igcurrencyeditor.component';
import { IgDateEditorComponent } from './modules/igeditors/igdateeditor.component';
import { IgDatePickerComponent } from './modules/igeditors/igdatepicker.component';
import { IgMaskEditorComponent } from './modules/igeditors/igmaskeditor.component';
import { IgNumericEditorComponent } from './modules/igeditors/ignumericeditor.component';
import { IgPercentEditorComponent } from './modules/igeditors/igpercenteditor.component';
import { IgTextEditorComponent } from './modules/igeditors/igtexteditor.component';
import { IgTreeComponent } from './modules/igtree/igtree.component';
import { IgDialogComponent } from './modules/igdialog/igdialog.component';
import { IgSplitterComponent } from './modules/igsplitter/igsplitter.component';
import { IgLayoutManagerComponent } from './modules/iglayoutmanager/iglayoutmanager.component';
import { IgTileManagerComponent } from './modules/igtilemanager/igtilemanager.component';
import { IgHtmlEditorComponent } from './modules/ightmleditor/ightmleditor.component';
import { IgValidatorComponent } from './modules/igvalidator/igvalidator.component';
import { IgPivotDataSelectorComponent } from './modules/igpivotdataselector/igpivotdataselector.component';
import { IgPivotGridComponent } from './modules/igpivotgrid/igpivotgrid.component';
import { IgDataChartComponent } from './modules/igdatachart/igdatachart.component';
import { IgPieChartComponent } from './modules/igpiechart/igpiechart.component';
import { IgDoughnutChartComponent } from './modules/igdoughnutchart/igdoughnutchart.component';
import { IgFunnelChartComponent } from './modules/igfunnelchart/igfunnelchart.component';
import { IgRadialGaugeComponent } from './modules/igradialgauge/igradialgauge.component';
import { IgZoombarComponent } from './modules/igzoombar/igzoombar.component';
import { IgMapComponent } from './modules/igmap/igmap.component';
import { IgSparklineComponent } from './modules/igsparkline/igsparkline.component';
import { IgBulletGraphComponent } from './modules/igbulletgraph/igbulletgraph.component';
import { IgLinearGaugeComponent } from './modules/iglineargauge/iglineargauge.component';
import { IgQRCodeBarcodeComponent } from './modules/igqrcodebarcode/igqrcodebarcode.component';
import { IgUploadComponent } from './modules/igupload/igupload.component';
import { IgPopoverComponent } from './modules/igpopover/igpopover.component';
import { IgNotifierComponent } from './modules/ignotifier/ignotifier.component';
import { IgRatingComponent } from './modules/igrating/igrating.component';
import { IgVideoPlayerComponent } from './modules/igvideoplayer/igvideoplayer.component';
import { IgRadialMenuComponent } from './modules/igradialmenu/igradialmenu.component';
import { IgSplitButtonComponent } from './modules/igsplitbutton/igsplitbutton.component';
import { IgSpreadsheetComponent } from './modules/igspreadsheet/igspreadsheet.component';
import { IgSchedulerComponent } from './modules/igscheduler/igscheduler.component';

export { Column };
export { IgGridMultiColumnHeadersFeature };
export { IgGridSortingFeature };
export { IgGridFilteringFeature };
export { IgGridPagingFeature };
export { IgGridUpdatingFeature };
export { IgGridGroupByFeature };
export { IgGridColumnMovingFeature };
export { IgGridHidingFeature };
export { IgGridCellMergingFeature };
export { IgGridResponsiveFeature };
export { IgGridResizingFeature };
export { IgGridSelectionFeature };
export { IgGridRowSelectorsFeature };
export { IgGridSummariesFeature };
export { IgGridColumnFixingFeature };
export { IgGridTooltipsFeature };
export { IgGridAppendRowsOnDemandFeature };
export { Features };
export { IgGridComponent };
export { IgTreeGridComponent };
export { IgHierarchicalGridComponent };
export { IgComboComponent };
export { IgCheckboxEditorComponent };
export { IgCurrencyEditorComponent };
export { IgDateEditorComponent };
export { IgDatePickerComponent };
export { IgMaskEditorComponent };
export { IgNumericEditorComponent };
export { IgPercentEditorComponent };
export { IgTextEditorComponent };
export { IgTreeComponent };
export { IgDialogComponent };
export { IgSplitterComponent };
export { IgLayoutManagerComponent };
export { IgTileManagerComponent };
export { IgHtmlEditorComponent };
export { IgValidatorComponent };
export { IgPivotDataSelectorComponent };
export { IgPivotGridComponent };
export { IgDataChartComponent };
export { IgPieChartComponent };
export { IgDoughnutChartComponent };
export { IgFunnelChartComponent };
export { IgRadialGaugeComponent };
export { IgZoombarComponent };
export { IgMapComponent };
export { IgSparklineComponent };
export { IgBulletGraphComponent };
export { IgLinearGaugeComponent };
export { IgQRCodeBarcodeComponent };
export { IgUploadComponent };
export { IgPopoverComponent };
export { IgNotifierComponent };
export { IgRatingComponent };
export { IgVideoPlayerComponent };
export { IgRadialMenuComponent };
export { IgSplitButtonComponent };
export { IgSpreadsheetComponent };
export { IgSchedulerComponent };

@NgModule({
	declarations: [Column,IgGridMultiColumnHeadersFeature,IgGridSortingFeature,IgGridFilteringFeature,IgGridPagingFeature,IgGridUpdatingFeature,IgGridGroupByFeature,IgGridColumnMovingFeature,IgGridHidingFeature,IgGridCellMergingFeature,IgGridResponsiveFeature,IgGridResizingFeature,IgGridSelectionFeature,IgGridRowSelectorsFeature,IgGridSummariesFeature,IgGridColumnFixingFeature,IgGridTooltipsFeature,IgGridAppendRowsOnDemandFeature,Features,IgGridComponent,IgTreeGridComponent,IgHierarchicalGridComponent,IgComboComponent,IgCheckboxEditorComponent,IgCurrencyEditorComponent,IgDateEditorComponent,IgDatePickerComponent,IgMaskEditorComponent,IgNumericEditorComponent,IgPercentEditorComponent,IgTextEditorComponent,IgTreeComponent,IgDialogComponent,IgSplitterComponent,IgLayoutManagerComponent,IgTileManagerComponent,IgHtmlEditorComponent,IgValidatorComponent,IgPivotDataSelectorComponent,IgPivotGridComponent,IgDataChartComponent,IgPieChartComponent,IgDoughnutChartComponent,IgFunnelChartComponent,IgRadialGaugeComponent,IgZoombarComponent,IgMapComponent,IgSparklineComponent,IgBulletGraphComponent,IgLinearGaugeComponent,IgQRCodeBarcodeComponent,IgUploadComponent,IgPopoverComponent,IgNotifierComponent,IgRatingComponent,IgVideoPlayerComponent,IgRadialMenuComponent,IgSplitButtonComponent, IgSpreadsheetComponent, IgSchedulerComponent],
	exports: [Column, IgGridMultiColumnHeadersFeature, IgGridSortingFeature,IgGridFilteringFeature,IgGridPagingFeature,IgGridUpdatingFeature,IgGridGroupByFeature,IgGridColumnMovingFeature,IgGridHidingFeature,IgGridCellMergingFeature,IgGridResponsiveFeature,IgGridResizingFeature,IgGridSelectionFeature,IgGridRowSelectorsFeature,IgGridSummariesFeature,IgGridColumnFixingFeature,IgGridTooltipsFeature,IgGridAppendRowsOnDemandFeature,Features,IgGridComponent,IgTreeGridComponent,IgHierarchicalGridComponent,IgComboComponent,IgCheckboxEditorComponent,IgCurrencyEditorComponent,IgDateEditorComponent,IgDatePickerComponent,IgMaskEditorComponent,IgNumericEditorComponent,IgPercentEditorComponent,IgTextEditorComponent,IgTreeComponent,IgDialogComponent,IgSplitterComponent,IgLayoutManagerComponent,IgTileManagerComponent,IgHtmlEditorComponent,IgValidatorComponent,IgPivotDataSelectorComponent,IgPivotGridComponent,IgDataChartComponent,IgPieChartComponent,IgDoughnutChartComponent,IgFunnelChartComponent,IgRadialGaugeComponent,IgZoombarComponent,IgMapComponent,IgSparklineComponent,IgBulletGraphComponent,IgLinearGaugeComponent,IgQRCodeBarcodeComponent,IgUploadComponent,IgPopoverComponent,IgNotifierComponent,IgRatingComponent,IgVideoPlayerComponent,IgRadialMenuComponent,IgSplitButtonComponent, IgSpreadsheetComponent, IgSchedulerComponent]
})
export class IgniteUIModule {}